apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "exploitableapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "exploitableapp.name" . }}
    chart: {{ template "exploitableapp.chart" . }}
    draft: {{ default "draft-app" .Values.draft }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "exploitableapp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "exploitableapp.name" . }}
        draft: {{ default "draft-app" .Values.draft }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: sharedfiles
          emptyDir: {}
      containers:
        - name: {{ template "exploitableapp.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: sharedfiles
              mountPath: /app/sharedfiles/
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            - name: Flag
              value: "{{ .Values.flag }}"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: USEMYSQL
              value: "false"
            - name: USEPOSTGRES
              value: "true"
            - name: DB_SERVER
              value: "{{ .Values.dbServer }}"
            - name: WEBSERVER_SERVICE_ENDPOINT
              value: "http://{{ .Values.webServer }}:8080"
            - name: WEBSERVICE_ENDPOINT
              value: "http://{{ .Values.webServiceServer }}:8080"
            - name: REDIS_SERVER
              value: "{{ .Values.redisServer }}"
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "exploitableapp.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
