version: '3.4'

services:
  app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - USEMYSQL=true
      - DISABLE_AUTOMATIC_KEY_GENERATION=true
  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - USEMYSQL=true
      - DISABLE_AUTOMATIC_KEY_GENERATION=true
  app3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - USEMYSQL=true
      - DISABLE_AUTOMATIC_KEY_GENERATION=true
    
  exploitableapp-ws:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - USEMYSQL=true
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=Password1
      - MYSQL_DATABASE=ExploitableDB
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=Password1

volumes:
  sharedfiles: {}
