#apiVersion: apps/v1
#kind: Ingress
#metadata:
#  namespace: {{ .Release.Namespace }}
#  name: {{ printf "%s-%s" .Release.Name  "guacamole-ingress" }}
#  labels:
#    io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacamole-ingress" }}
#  annotations:
#    ingress.kubernetes.io/proxy-body-size: '0'
#    ingress.kubernetes.io/ssl-redirect: 'false'
#    nginx.ingress.kubernetes.io/proxy-body-size: '0'
#    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
#    nginx.ingress.kubernetes.io/affinity: 'cookie'
#    nginx.ingress.kubernetes.io/session-cookie-name: 'route'
#    nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
#    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
#    #kubernetes.io/ingress.class: "nginx"    
#    kubernetes.io/ingress.class: "addon-http-application-routing""
#    #certmanager.k8s.io/issuer: "letsencrypt-staging"
#    #certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
#    certmanager.k8s.io/issuer: "letsencrypt-prod"
#    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
#spec:
#  tls:
#  - hosts:
#    - {{ .Values.hostName }}
#    secretName: exploitable-tls
#  rules:
#  - host: {{ .Values.hostName }}
#    http:
#      paths:
#      - path: "/guacamole/"
#        backend:
#          serviceName: {{ printf "%s-%s" .Release.Name  "guacamole" }}
#          servicePort: 8080
#status:
#  loadBalancer:
#    ingress:
#    - {}