apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "db.name" . }}
    helm.sh/chart: {{ include "db.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
